### ISSUE TITLE
Error on Preview in CRUD Generator

### ISSUE THREAD

**Issue by puresourcellc** [rcoelho/giix#1]
Hi,

Here is the error:
Property "CPhpMessageSource.extensionBasePaths" is not defined.

I'm using Yii 1.10

**Comment by diegoviola1** [comment]
Hi,

if you check readme you can see this:
- Bundled translations (pending support on Yii core as of Yii 1.1.8. See http://code.google.com/p/yii/issues/detail?id=2624 for details).

Fixing this file you can use the extension.

**Comment by puresourcellc** [comment]
Hi Diego,

Thanks for the pointer on this!

Sincerely,

## 

H. Lloyd Samuels
CEO, Pure Source LLC
1375 Broadway
3rd Floor
New York, NY 10018
646-467-7377

On 6/26/12 1:51 PM, "Diego Viola"
<reply+i-5202949-f0b4648efa6f512ffd92c5dd206adc10fb46c3cb-419400@reply.gith
ub.com> wrote:

**Comment by diegoviola1** [comment]
You are welcome!

**Comment by rcoelho** [comment]
@diegoviola1 thanks for helping @hsamuels with this issue. I'm closing it.

**Comment by LeiLiTroy** [comment]
What you mean by fixing the file? I have tried everything, so far nothing worked.

**Comment by rcoelho** [comment]
You need to patch the file and follow the instructions on that link.
